baseURL = "https://blog.tdhttt.com/"
languageCode = "en-us"
title = "Tony Tong"
pluralizelisttitles = false
theme = "casper"
paginate = 5
DisqusShortname = "tdhttt"
Copyright = "All rights reserved - 2022"
canonifyurls = true

[params]
  description = "Random thoughts" 
  # metadescription = "Used as 'description' meta tag for both home and index pages. If not set, 'description' will be used instead"
  cover = "images/smallp-bigm-small.jpg"
  shareimg = "images/land_t_dark.png"
  author = "Tony Tong"
  # authorlocation = "Paris, France"
  authorwebsite = "https://tdhttt.com/"
  authorbio= "Radom thoughts."
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-142543240-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  githubName = "TDHTTTT"
  twitterName = "tdhttt"
  # facebookName = ""
  # codepenName = ""
  linkedinName = "tdhttt"
  stackoverflowId = "7327352"
  keybaseName = "tdhttt"
  # flickrName = ""
  # instagramName = ""
  # email = ""
  # pinterestName = ""
  # googlePlusName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false 
  
  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "default"


[[menu.main]]
  name = "Portal"
  weight = -110
  identifier = "portal"
  url = "https://tdhttt.com/"

[[menu.main]]
  name = "About me"
  weight = -120
  identifier = "about"
  url = "/post/"
